In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
#generating random data
xs = np.random.uniform(-10,10,size=(1000,1))
zs = np.random.uniform(-10,10,size=(1000,1))
noise = np.random.uniform(-1,1,size=(1000,1))

generated_inputs = np.column_stack((xs,zs))
generated_targets = 2 * xs - 3 * zs + 5 + noise

#saving the data as npz file
np.savez("TF_intro",inputs = generated_inputs, targets = generated_targets)

In [3]:
#Loading the npz file
training_data = np.load("TF_intro.npz")

In [4]:
#model
input_size = 2
output_size = 1

model = tf.keras.Sequential([
    tf.keras.layers.Dense(
        output_size,
        kernel_initializer = tf.random_uniform_initializer(-0.1,0.1),
        bias_initializer = tf.random_uniform_initializer(-0.1,0.1)       
    )
    ])

custom_optimiser = tf.keras.optimizers.SGD(learning_rate=0.02)
model.compile(optimizer=custom_optimiser,loss="mean_squared_error")
model.fit(training_data["inputs"], training_data["targets"], epochs=100,verbose=2)

Epoch 1/100
32/32 - 0s - 9ms/step - loss: 34.4468
Epoch 2/100
32/32 - 0s - 2ms/step - loss: 1.3602
Epoch 3/100
32/32 - 0s - 2ms/step - loss: 0.4773
Epoch 4/100
32/32 - 0s - 1ms/step - loss: 0.3673
Epoch 5/100
32/32 - 0s - 2ms/step - loss: 0.3902
Epoch 6/100
32/32 - 0s - 2ms/step - loss: 0.3861
Epoch 7/100
32/32 - 0s - 1ms/step - loss: 0.3835
Epoch 8/100
32/32 - 0s - 1ms/step - loss: 0.3713
Epoch 9/100
32/32 - 0s - 1ms/step - loss: 0.3771
Epoch 10/100
32/32 - 0s - 2ms/step - loss: 0.4142
Epoch 11/100
32/32 - 0s - 1ms/step - loss: 0.4019
Epoch 12/100
32/32 - 0s - 2ms/step - loss: 0.4250
Epoch 13/100
32/32 - 0s - 2ms/step - loss: 0.3905
Epoch 14/100
32/32 - 0s - 2ms/step - loss: 0.3973
Epoch 15/100
32/32 - 0s - 2ms/step - loss: 0.3971
Epoch 16/100
32/32 - 0s - 2ms/step - loss: 0.4029
Epoch 17/100
32/32 - 0s - 2ms/step - loss: 0.3878
Epoch 18/100
32/32 - 0s - 2ms/step - loss: 0.3840
Epoch 19/100
32/32 - 0s - 2ms/step - loss: 0.3605
Epoch 20/100
32/32 - 0s - 1ms/step - loss: 0.3906
Epoch 21

In [5]:
#weights and biases
model.layers[0].get_weights()

[array([[ 1.9889836],
        [-3.0160694]], dtype=float32),
 array([5.0110173], dtype=float32)]

In [6]:
weights = model.layers[0].get_weights()[0]
bias = model.layers[0].get_weights()[1]

weights, bias

(array([[ 1.9889836],
        [-3.0160694]], dtype=float32),
 array([5.0110173], dtype=float32))