In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
#random data
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [3]:
x_train, y_train = train_test_split(a,test_size=0.2,random_state=10)

In [4]:
x_train

array([ 91,  71,  51,  45,  77,  56,  22,  62,   7,  64,  43,  35,  85,
        53,  36,  40,  46,   5,   6,  49,  33,  21,  84,  59,  48,  81,
        18,  68,  82,   8,  88,  98,  99, 100,  25,  11,  97,  87,  57,
        72,  24,  23,  92,  95,  19,  28,  89,  58,  32,  66,  13,  83,
        31,  76,  26,  14,  70,  78,  86,  52,  50,  79,  73,  34,  63,
        55,  12,  17,  37,  41,   1,  74,   9,  30,  94,  90,  29,  65,
        16,  10])

In [5]:
y_train

array([20, 15, 44, 38, 67,  4, 80, 42, 39, 69,  3,  2, 61, 54, 96, 75, 93,
       27, 60, 47])